# Generated by Django 5.0.2 on 2024-02-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Designation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
