# Generated by Django 5.0.2 on 2024-02-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userdetails_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
