# Generated by Django 5.0.2 on 2024-02-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userdetails_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='skills',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
