# Generated by Django 5.0.2 on 2024-02-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userdetails_last_name_userdetails_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
