# Generated by Django 5.0.2 on 2024-02-11 12:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_userdetails_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
