# Generated by Django 5.0.2 on 2024-02-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_userdetails_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='avgrating',
            field=models.IntegerField(default=0),
        ),
    ]
