# Generated by Django 5.0.2 on 2024-02-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_userdetails_avgrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='avgrating',
            field=models.FloatField(default=0),
        ),
    ]
